# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LSiOHApwXyiszHkj/4IH5ERJDy9SXmli3AApueK6qkeXv8Q+WHSWQjnLs9JWYA/A8xZLIFP9QgmcwUzKcVgS0MYdMMkL6+8OC1XSv+tgTltudzpB/PrUNaPHsY+UjQ9nIQSIaR6hl7Jb2azk82PwWELYDfyxntZpiM1aFfKmobWss6N6uHD6ie9xdfMW7rNSNSfCGivjqBYhOUseeE4rxZeL8ElHcFbzv6baJX8H5WTsil2r+NpS5NHtSGNShT272R1ejVKz/lM6wz7ZJPiaGaetJBPI5ytJiKelQVJCzhh48yEG8eOY3xt1HW5sV23KKXx82pAU2ijkooOYkqDMXBNgbWj+VsNidgPXdtUK5QVEHjsxfN9CxbLDnK0zKg+vSMZSGRfOrIMk8p4nbVB0MCUTfsSDQwm3jDKeGOuJxGWaMdp6PN1eK852gH0MU0peixVzaCKiRHVtBpIKGJzHCotwU/EJYKxllzQln5w2wx5QSDJIir4frMYASu+21wJNChYmv1pyQCHItfKxv9C6H8782ch1HYVOkdezxBY7OfMszeZ1gjY+2L8YTm9ckPoGO9dFMqfRMhCc3YiLzoZnKPf6cDAnPr+z/2I3zKGWeRwsxDVFwxWc67hCQN/+sguNGHuv9GxRzcZNAUeS1698Wps639Ly731QuoWUbrNdVm8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml